sudo: false

language:
  - python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - pycodestyle webresourcecrawler
#  - pytest --verbose --capture=no webresourcecrawler
  - pip install .

notifications:
  email: false
